spring:
  application:
    name: zero-gap
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/zero_gap_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password1!}
  jpa:
    database: mysql
    show-sql: true
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        project-id: gdg-hackathon-486210
